/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class poo_01_SaoriApaza extends javax.swing.JFrame {
    double PrimerNumero;//40
    double SegundoNumero;//10
    double Resultado;//30
    String Operador;//-

    /**
     * Creates new form poo_01_SaoriApaza
     */
    public poo_01_SaoriApaza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JTextField();
        N1 = new javax.swing.JButton();
        N2 = new javax.swing.JButton();
        N3 = new javax.swing.JButton();
        N4 = new javax.swing.JButton();
        N5 = new javax.swing.JButton();
        N6 = new javax.swing.JButton();
        N7 = new javax.swing.JButton();
        N8 = new javax.swing.JButton();
        N9 = new javax.swing.JButton();
        N0 = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnDivi = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(310, 455));
        setMinimumSize(new java.awt.Dimension(310, 455));
        setResizable(false);
        getContentPane().setLayout(null);

        Pantalla.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        Pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(Pantalla);
        Pantalla.setBounds(40, 50, 210, 40);

        N1.setBackground(new java.awt.Color(61, 38, 73));
        N1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        N1.setForeground(new java.awt.Color(255, 255, 255));
        N1.setText("1");
        N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N1ActionPerformed(evt);
            }
        });
        getContentPane().add(N1);
        N1.setBounds(30, 230, 50, 50);

        N2.setBackground(new java.awt.Color(61, 38, 73));
        N2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        N2.setForeground(new java.awt.Color(255, 255, 255));
        N2.setText("2");
        N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N2ActionPerformed(evt);
            }
        });
        getContentPane().add(N2);
        N2.setBounds(90, 230, 50, 50);

        N3.setBackground(new java.awt.Color(61, 38, 73));
        N3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        N3.setForeground(new java.awt.Color(255, 255, 255));
        N3.setText("3");
        N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N3ActionPerformed(evt);
            }
        });
        getContentPane().add(N3);
        N3.setBounds(150, 230, 50, 50);

        N4.setBackground(new java.awt.Color(61, 38, 73));
        N4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        N4.setForeground(new java.awt.Color(255, 255, 255));
        N4.setText("4");
        N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N4ActionPerformed(evt);
            }
        });
        getContentPane().add(N4);
        N4.setBounds(30, 170, 50, 50);

        N5.setBackground(new java.awt.Color(61, 38, 73));
        N5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        N5.setForeground(new java.awt.Color(255, 255, 255));
        N5.setText("5");
        N5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N5ActionPerformed(evt);
            }
        });
        getContentPane().add(N5);
        N5.setBounds(90, 170, 50, 50);

        N6.setBackground(new java.awt.Color(61, 38, 73));
        N6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        N6.setForeground(new java.awt.Color(255, 255, 255));
        N6.setText("6");
        N6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N6ActionPerformed(evt);
            }
        });
        getContentPane().add(N6);
        N6.setBounds(150, 170, 50, 50);

        N7.setBackground(new java.awt.Color(61, 38, 73));
        N7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        N7.setForeground(new java.awt.Color(255, 255, 255));
        N7.setText("7");
        N7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N7ActionPerformed(evt);
            }
        });
        getContentPane().add(N7);
        N7.setBounds(30, 110, 50, 50);

        N8.setBackground(new java.awt.Color(61, 38, 73));
        N8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        N8.setForeground(new java.awt.Color(255, 255, 255));
        N8.setText("8");
        N8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N8ActionPerformed(evt);
            }
        });
        getContentPane().add(N8);
        N8.setBounds(90, 110, 50, 50);

        N9.setBackground(new java.awt.Color(61, 38, 73));
        N9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        N9.setForeground(new java.awt.Color(255, 255, 255));
        N9.setText("9");
        N9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N9ActionPerformed(evt);
            }
        });
        getContentPane().add(N9);
        N9.setBounds(150, 110, 50, 50);

        N0.setBackground(new java.awt.Color(61, 38, 73));
        N0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        N0.setForeground(new java.awt.Color(255, 255, 255));
        N0.setText("0");
        N0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0ActionPerformed(evt);
            }
        });
        getContentPane().add(N0);
        N0.setBounds(30, 290, 50, 40);

        btnSuma.setBackground(new java.awt.Color(61, 38, 73));
        btnSuma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(255, 255, 255));
        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuma);
        btnSuma.setBounds(210, 230, 50, 100);

        btnResta.setBackground(new java.awt.Color(61, 38, 73));
        btnResta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnResta.setForeground(new java.awt.Color(255, 255, 255));
        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnResta);
        btnResta.setBounds(210, 200, 50, 23);

        btnDivi.setBackground(new java.awt.Color(61, 38, 73));
        btnDivi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDivi.setForeground(new java.awt.Color(255, 255, 255));
        btnDivi.setText("/");
        btnDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiviActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivi);
        btnDivi.setBounds(210, 140, 50, 23);

        btnMulti.setBackground(new java.awt.Color(61, 38, 73));
        btnMulti.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMulti.setForeground(new java.awt.Color(255, 255, 255));
        btnMulti.setText("x");
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });
        getContentPane().add(btnMulti);
        btnMulti.setBounds(210, 170, 50, 20);

        btnPunto.setBackground(new java.awt.Color(61, 38, 73));
        btnPunto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPunto.setForeground(new java.awt.Color(255, 255, 255));
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPunto);
        btnPunto.setBounds(90, 290, 50, 40);

        btnIgual.setBackground(new java.awt.Color(46, 29, 55));
        btnIgual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(255, 255, 255));
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        getContentPane().add(btnIgual);
        btnIgual.setBounds(150, 290, 50, 40);

        btnLimpiar.setBackground(new java.awt.Color(61, 38, 73));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("C");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(210, 110, 50, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\omagen de calculadora\\image-removebg-preview (41).png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 310, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
    String Numero = Pantalla.getText()+btnPunto.getText();
    Pantalla.setText(Numero);
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiviActionPerformed
    PrimerNumero = Double.parseDouble(Pantalla.getText());
    Pantalla.setText(" ");
    Operador = "/";
    }//GEN-LAST:event_btnDiviActionPerformed

    private void N0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0ActionPerformed
    String Numero = Pantalla.getText()+N0.getText();
    Pantalla.setText(Numero);
    }//GEN-LAST:event_N0ActionPerformed

    private void N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1ActionPerformed
    String Numero = Pantalla.getText()+N1.getText();
    Pantalla.setText(Numero);
    }//GEN-LAST:event_N1ActionPerformed

    private void N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ActionPerformed
    String Numero = Pantalla.getText()+N2.getText();
    Pantalla.setText(Numero);
    }//GEN-LAST:event_N2ActionPerformed

    private void N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N3ActionPerformed
    String Numero = Pantalla.getText()+N3.getText();
    Pantalla.setText(Numero);
    }//GEN-LAST:event_N3ActionPerformed

    private void N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N4ActionPerformed
    String Numero = Pantalla.getText()+N4.getText();
    Pantalla.setText(Numero);
    }//GEN-LAST:event_N4ActionPerformed

    private void N5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N5ActionPerformed
    String Numero = Pantalla.getText()+N5.getText();
    Pantalla.setText(Numero);
    }//GEN-LAST:event_N5ActionPerformed

    private void N6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N6ActionPerformed
    String Numero = Pantalla.getText()+N6.getText();
    Pantalla.setText(Numero);
    }//GEN-LAST:event_N6ActionPerformed

    private void N7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N7ActionPerformed
    String Numero = Pantalla.getText()+N7.getText();
    Pantalla.setText(Numero);
    }//GEN-LAST:event_N7ActionPerformed

    private void N8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N8ActionPerformed
    String Numero = Pantalla.getText()+N8.getText();
    Pantalla.setText(Numero);
    }//GEN-LAST:event_N8ActionPerformed

    private void N9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N9ActionPerformed
    String Numero = Pantalla.getText()+N9.getText();
    Pantalla.setText(Numero);
    }//GEN-LAST:event_N9ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    Pantalla.setText(" ");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
    PrimerNumero = Double.parseDouble(Pantalla.getText());
    Pantalla.setText(" ");
    Operador = "+";
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
    PrimerNumero = Double.parseDouble(Pantalla.getText());
    Pantalla.setText(" ");
    Operador = "-";
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
    PrimerNumero = Double.parseDouble(Pantalla.getText());
    Pantalla.setText(" ");
    Operador = "*";
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
    SegundoNumero = Double.parseDouble(Pantalla.getText());
    
    if(Operador.equals("+")){
        Resultado = PrimerNumero + SegundoNumero;
        Pantalla.setText(Double.toString(Resultado));
    }else if(Operador.equals("-")){
        Resultado = PrimerNumero - SegundoNumero;
        Pantalla.setText(Double.toString(Resultado));
    }else if(Operador.equals("*")){
        Resultado = PrimerNumero * SegundoNumero;
        Pantalla.setText(Double.toString(Resultado));
    }else if(Operador.equals("/")){
        Resultado = PrimerNumero / SegundoNumero;
        Pantalla.setText(Double.toString(Resultado));
    }      
    
    }//GEN-LAST:event_btnIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(poo_01_SaoriApaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(poo_01_SaoriApaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(poo_01_SaoriApaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(poo_01_SaoriApaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new poo_01_SaoriApaza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton N0;
    private javax.swing.JButton N1;
    private javax.swing.JButton N2;
    private javax.swing.JButton N3;
    private javax.swing.JButton N4;
    private javax.swing.JButton N5;
    private javax.swing.JButton N6;
    private javax.swing.JButton N7;
    private javax.swing.JButton N8;
    private javax.swing.JButton N9;
    private javax.swing.JTextField Pantalla;
    private javax.swing.JButton btnDivi;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
